### ISSUE TITLE
Все работает, но без автозапуска

### ISSUE THREAD

**Issue by Naz1anmak** [Tess-OK/AutoClickerBlum#2]
Автор молодец, но со значениями поигрался, а автозапуск игры не работает, нужно самому нажимать play

**Comment by aigiz96** [comment]
Все работал, но игру обновили ждем обновление кликера

**Comment by Naz1anmak** [comment]
> Все работало, но игру обновили ждем обновление кликера

Я заменил скриншоты в папке на свои, все заработало)
